var series = {
  1: {
    '1': 'Pilot',
    '2': 'The Aftermath',
    '3': 'Blind Date',
    '4': 'Jack the Writer',
    '5': 'Jack-Tor',
    '6': 'Jack Meets Dennis',
    '7': 'Tracy Does Conan',
    '8': 'The Break-Up',
    '9': 'The Baby Show',
    '10': 'The Rural Juror',
    '11': 'The Head and the Hair',
    '12': 'Black Tie',
    '13': 'Up All Night',
    '14': 'The C Word',
    '15': 'Hard Ball',
    '16': 'The Source Awards',
    '17': 'The Fighting Irish',
    '18': 'Fireworks',
    '19': 'Corporate Crush',
    '20': 'Cleveland',
    '21': 'Hiatus'
  },
  2: {
    '1': 'SeinfeldVision',
    '2': 'Jake Gets in the Game',
    '3': 'The Collection',
    '4': 'Rosemary\'s Baby',
    '5': 'Greenzo',
    '6': 'Somebody to Love',
    '7': 'Cougars',
    '8': 'Secrets and Lies',
    '9': 'Ludachristmas',
    '10': 'Episode 210',
    '11': 'MILF Island',
    '12': 'Subway Hero',
    '13': 'Succession',
    '14': 'Sandwich Day',
    '15': 'Cooter'
  },
  3: {
    '1': 'Do-Over',
    '2': 'Believe in the Stars',
    '3': 'The One with the Cast of Night Court',
    '4': 'Gavin Volure',
    '5': 'Reunion',
    '6': 'Christmas Special',
    '7': 'Señor Macho Solo',
    '8': 'Flu Shot',
    '9': 'Retreat to Move Forward',
    '10': 'Generalissimo',
    '11': 'St. Valentine\'s Day',
    '12': 'Larry King',
    '13': 'Goodbye, My Friend',
    '14': 'The Funcooker',
    '15': 'The Bubble',
    '16': 'Apollo, Apollo',
    '17': 'Cutbacks',
    '18': 'Jackie Jormp-Jomp',
    '19': 'The Ones',
    '20': 'The Natural Order',
    '21': 'Mamma Mia',
    '22': 'Kidney Now!'
  },
  4: {
    '1': 'Season 4',
    '2': 'Into the Crevasse',
    '3': 'Stone Mountain',
    '4': 'Audition Day',
    '5': 'The Problem Solvers',
    '6': 'Sun Tea',
    '7': 'Dealbreakers TAlk Show #0001',
    '8': 'Secret Santa',
    '9': 'Klaus and Greta',
    '10': 'Black Light Attack!',
    '11': 'Winter Madness',
    '12': 'Verna',
    '13': 'Anna Howard Shaw Day',
    '14': 'Future Husband',
    '15': 'Don Geiss, America and Hope',
    '16': 'Floyd',
    '17': 'Lee Marvin vs. Derek Jeter',
    '18': 'Khonani',
    '19': 'Argus',
    '20': 'The Moms',
    '21': 'Emanuelle Goes to Dinosaur Land',
    '22': 'I Do Do'
  },
  5: {
    '1': 'The Fabian Strategy',
    '2': 'When It Rains, It Pours',
    '3': 'Let\'s Stay Together',
    '4': 'Live Show',
    '5': 'Reaganing',
    '6': 'Gentleman\'s Intermission',
    '7': 'Brooklyn Without Limits',
    '8': 'College',
    '9': 'Chain Reaction of Mental Anguish',
    '10': 'Christmas Attack Zone',
    '11': 'Mrs. Donaghy',
    '12': 'Operation Righteous Cowboy Lightning',
    '13': '¡Qué Sorpresa!',
    '14': 'Double-Edged Sword',
    '15': 'It\'s Never Too Late for Now',
    '16': 'TGS Hates Women',
    '17': 'Queen of Jordan',
    '18': 'Plan B',
    '19': 'I Heart Connecticut',
    '20 & 21': '100',
    '22': 'Everything Sunny All the Time Always',
    '23': 'Respawn'
  },
  6: {
    '1': 'Dance Like Nobody\'s Watching',
    '2': 'Idiots Are People Two!',
    '3': 'Idiots Are People Three!',
    '4': 'The Ballad of Kenneth Parcell',
    '5': 'Today You Are a Man',
    '6 & 7': 'Hey, Baby, What\'s Wrong',
    '8': 'The Tuxedo Begins',
    '9': 'Leap Day',
    '10': 'Alexis Goodlooking and the Case of the Missing Whisky',
    '11': 'Standards and Practices',
    '12': 'St. Patrick\'s Day',
    '13': 'Grandmentor',
    '14': 'Kidnapped by Danger',
    '15': 'The Shower Principle',
    '16': 'Nothing Left to Lose',
    '17': 'Meet the Woggels!',
    '18': 'Murphy Brown Lied to Us',
    '19': 'Live from Studio 6H',
    '20': 'Queen of Jordan 2: Myster of the Phantom Pooper',
    '21': 'The Return of Avery Jessup',
    '22': 'What Will Happen to the Gang Next Year?'
  },
  7: {
    '1': 'The Beginning of the End',
    '2': 'Governor Dunston',
    '3': 'Stride of Pride',
    '4': 'Unwindulax',
    '5': 'There\'s No I in America',
    '6': 'Aunt Phatso vs. Jack Donaghy',
    '7': 'Mazel Tov, Dummies!',
    '8': 'My Whole Life Is Thunder',
    '9': 'Game Over',
    '10': 'Florida',
    '11': 'A Goon\'s Deed in a Weary World',
    '12': 'Hogcock!',
    '13': 'Last Lunch'
  }
};
